%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/zed2/zed_node/imu/data"
image0_topic: "/zed2/zed_node/left/image_rect_color"
image1_topic: "/zed2/zed_node/right/image_rect_color"
output_path: "/home/bhjx/project/vins_ws/output/"

cam0_calib: "cam0.yaml"
cam1_calib: "cam1.yaml"
image_width: 1280
image_height: 720
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

# camera to imu T
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data:  [0.009202815356381983, 0.0016383001968379718, 0.9999563111266327, -0.021978246509585596,
           -0.999951880974656, 0.0034128520230093384, 0.00919718306430184,  0.001735028941512754,
           -0.0033976351725248377, -0.9999928341810935, 0.0016696292104356747, 0.03888012121340217,
           0, 0, 0, 1]



body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data:  [0.004977461829550861, 0.0012904017688988856, 0.9999867797811179, 0.09718284091822599,
           -0.9999829004468719, 0.0030762609808962227, 0.004973472854966243, 0.0019092121258369617,
          -0.0030698025338830592, -0.9999944357253456, 0.0013056916752154368, 0.039144107191999226,
          0, 0, 0, 1]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 2.9752199084974767e-02          # accelerometer measurement noise standard deviation. 
gyr_n: 1.8859041916749149e-02         # gyroscope measurement noise standard deviation.     
acc_w: 6.4581594699404568e-04       # accelerometer bias random work noise standard deviation.  
gyr_w: 7.1571870936377460e-04       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
#td: 0.0025543627810018523
td: 0                    
#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/bhjx/project/vins_ws/output/pose_graph" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 

